COS mapping init
hmcts/prl-cos-api pull request #1610
Opened 2023-08-10 09:19 UTC by hmcts-shajahan

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] the `keep-helm` label has been added, if the helm release should be persisted after a successful build

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2023-08-16 16:41 UTC, channa-patil requested changes

2023-08-16 17:28 UTC, hmcts-shajahan commented on src/main/java/uk/gov/hmcts/reform/prl/mapper/citizen/CaseDataMapper.java
> +                                                    c100RebuildChildDetailsElements.getChildDetails());
Resolved

2023-08-16 17:30 UTC, hmcts-shajahan commented on src/main/java/uk/gov/hmcts/reform/prl/mapper/citizen/CaseDataSafetyConcernsElementsMapper.java
> +        if (isNotEmpty(childAbuse.getPhysicalAbuse()) && abuseType.equals(ChildAbuseEnum.physicalAbuse)) {
resolved

2023-08-16 21:14 UTC, hmcts-shajahan commented on src/main/java/uk/gov/hmcts/reform/prl/mapper/citizen/CaseDataSafetyConcernsElementsMapper.java
> +                                                                        List<ChildDetail> childDetails) {
resolved

2023-08-18 10:42 UTC, hmcts-shajahan commented on src/main/java/uk/gov/hmcts/reform/prl/mapper/citizen/CaseDataSafetyConcernsElementsMapper.java
> +        return applicantElements;
resolved

2023-08-18 13:16 UTC, channa-patil approved these changes

2023-08-18 13:45 UTC, merged