Reduced cognitive compexity
hmcts/prl-cos-api pull request #1827
Opened 2023-10-31 13:02 UTC by BharadwajSairam

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] the `enable_keep_helm` label has been added, if the helm release should be persisted after a successful build

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2023-10-31 23:49 UTC, AlokDatta requested changes

2023-10-31 23:49 UTC, AlokDatta commented on src/main/java/uk/gov/hmcts/reform/prl/controllers/ManageOrdersController.java
> +    }
is this change relevant?

2023-11-01 10:12 UTC, BharadwajSairam commented on src/main/java/uk/gov/hmcts/reform/prl/controllers/ManageOrdersController.java
> +    }
Removed and resolved

2023-11-01 10:37 UTC, AlokDatta approved these changes

2023-11-01 10:50 UTC, shashisk97 approved these changes
LGTM

2023-11-01 11:11 UTC, merged