HwF processing- Cron job for checking payment status
hmcts/prl-cos-api pull request #2470
Opened 2024-06-18 12:33 UTC by sahaSonali

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] the `enable_keep_helm` label has been added, if the helm release should be persisted after a successful build

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/PRL-5906

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2024-06-24 11:14 UTC, channa-patil requested changes

2024-06-24 11:14 UTC, channa-patil commented on src/main/java/uk/gov/hmcts/reform/prl/models/c100rebuild/C100RebuildHelpWithFeesElements.java
> +    private String helpWithFeesReferenceNumber;
@sahaSonali Please remove this field if we are not getting it from UI.

2024-06-24 11:14 UTC, channa-patil commented on src/main/java/uk/gov/hmcts/reform/prl/services/HwfProcessUpdateCaseStateService.java
> +                    if (!PaymentStatus.PAID.getDisplayedValue().equals(paymentGroupReferenceStatusResponse.getServiceRequestStatus())) {
@sahaSonali Please correct it & also check if we need anything to handle partial remissions.

2024-06-24 11:14 UTC, channa-patil commented on src/main/java/uk/gov/hmcts/reform/prl/clients/PaymentApi.java
> +        @PathVariable("payment-group-reference") String paymentGroupReference
Can we please rename this to request request reference.

2024-06-25 15:36 UTC, yogendraU approved these changes

2024-08-28 16:32 UTC, merged